### ISSUE TITLE
Qr Scanner window

### ISSUE THREAD

**Issue by anubhavtripathi0509** [RJGATON007/gyms#34]
The camera is not closing after clicking the close icon, bug have been displayed into below file

https://github.com/RJGATON007/gyms/assets/115779904/8a4dd44f-7b94-4158-95f2-1dca4c32775d

**Comment by anubhavtripathi0509** [comment]
Bug is at this window, the QR code Scanner is not closing after clicking the cross icon on window.

![Screenshot 2024-02-06 101357](https://github.com/RJGATON007/gyms/assets/115779904/9f5f0f1b-501c-434f-bb33-250a890fc0d5)

**Comment by RJGATON007** [comment]
That's because i haven't fixed it yet. try pressing 'Q' in your key board.
the camera will exit.

I have some changes for that repo, but i still haven't committed it yet
because i'm too busy for my start of OJT.

**Comment by anubhavtripathi0509** [comment]
I have fixed that issue check out pull request

**Comment by RJGATON007** [comment]
thank you
